Fix ZEND_BEGIN_ARG_INFO_EX for ibase_rollback
When running a debug build of PHP, the engine verifies that the info
supplied in the `ZEND_BEGIN_ARG_INFO_EX` macro is correct. The last
parameter of the `ZEND_BEGIN_ARG_INFO_EX` macro is the number of
required arguments.

If we try to invoke `ibase_rollback` with zero arguments, we get the
following error message:

```
Fatal error: Arginfo / zpp mismatch during call of ibase_rollback() in test.php on line 123
```

This patch corrects this by setting the value to zero to match how the
method is implemented.